apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meetup-3
  annotations:
    "volume.alpha.kubernetes.io/storage-class": "any"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
