apiVersion: v1
kind: PersistentVolume
metadata:
  name: meetup-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  gcePersistentDisk:
    pdName: meetup-2
  persistentVolumeReclaimPolicy: Retain
